lr: 0.001
fisher_alpha: 1
fisher_size: 2000
# e_margin: 0.921034037 # 0.4 * ln(num_classes) (current value for cifar10)
e_margin_coeff: 0.4
d_margin: 0.4
fisher_clip_by_norm: 10
nesterov: false
optimizer: sgd

# my modifications:
fisher_online: false
fisher_update_every: 100