lr: 1.e-3
optimizer: adam
beta: 0.9
weight_decay: 0.
steps: 1
episodic: false
mt: 0.999
rst: 0.01
ap: 0.92
nesterov: false

# my modifications:
distillation_temp: 1 # of ditillation loss of output
features_distillation: false # distillation on feature level