lr: 1.e-3
optimizer: sgd
beta: 0.9
weight_decay: 0.
steps: 1
nesterov: true

# -- my modifications --:

## distillation
distillation_out_temp: 1 # of ditillation loss of output
features_distillation_weight: 0 # distillation on feature level weight with respect to loss

## exemplars
exemplars: false
memory_per_class: 200
num_replay_samples: 10
replay_augs: cotta # none | cotta | mixup_from_memory | mixup_within_memory

num_first_blocks_for_update: -1

